# -*- coding: utf-8 -*-
"""pipeline function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13s4WHY7-Zh95OVQNNyb-q8eQBe5G0cL_
"""

!pip install transformers

from transformers import pipeline

# sentiment-analysis is the task
classifier = pipeline("sentiment-analysis")

classifier([
    "I have been waiting for a Hugging Face course my whole life",
    "I hate this too much"
])

"""2 - multiple classification"""

from transformers import pipeline
classifier = pipeline("zero-shot-classification")
classifier(
    "This is the code about the transformer library",
    candidate_labels=["education", "politics", "business"],
)

"""3. text generating"""

from transformers import pipeline
generator = pipeline("text-generation",model = "distilgpt2")
generator("In this course, we will teach you how to")

"""4 - Question Answering"""

from transformers import pipeline

question_answere = pipeline("question-answering")
question_answere(
    question = 'where do i work?',
    context = 'my name is kavinda and i work in primed pharmacy'
)

